{{- if .Values.callbackLBservice.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iobroker.fullname" . }}-callback
  labels:
    {{- include "iobroker.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.callbackLBservice.ip }}
  ports:
  {{- range .Values.callbackLBservice.ports }}
    - name: {{ .name }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      port: {{ .port }}
  {{- end }}  
  selector:
    {{- include "iobroker.selectorLabels" $ | nindent 4 }}
{{- end }}

