apiVersion: v1
kind: Service
metadata:
  name: {{ include "iobroker.fullname" . }}-admin
  labels:
    {{- include "iobroker.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "iobroker.selectorLabels" . | nindent 4 }}

{{- if .Values.additionalServices }}
{{- range .Values.additionalServices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iobroker.fullname" $ }}-{{ .name }}
  labels:
    {{- include "iobroker.labels" $ | nindent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: {{ .type }}
  {{- if .loadBalancerClass}}
  loadBalancerClass: {{.loadBalancerClass}}
  {{- end}}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
  selector:
    {{- include "iobroker.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end}}
