# Default values for mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mariadb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3306

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: mariadb.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
externalSecret:
  name: mariadb-external-secret-name
  secretStoreRef:
    name: secret-store
  targetSecretName: mariadb-secret-name
  refreshInterval: "3600s"
  secretKey:
    remoteRef:
      key: my-remote-ref
      

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

env:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mariadb-secret
        key: my-root-pw-key

# Additional volumes on the output StatefulSet definition.
volumes:
  - name: mariadb-data
    persistentVolumeClaim:
      claimName: mariadb-data-pvc
  - name: mariadb-backup
    persistentVolumeClaim:
      claimName: mariadb-backup-pvc
  - name: mariadb-config
    configMap:
      name: mariadb-configmap
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output StatefulSet definition.
volumeMounts: 
  - name: mariadb-config
    mountPath: /etc/mysql/conf.d
  - name: mariadb-data
    mountPath: /var/lib/mysql
  - name: mariadb-backup
    mountPath: /backup
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: 
   kubernetes.io/hostname: node_name

tolerations: []

affinity: {}

persistence:
  enabled: true
  annotations: {} 
  accessMode: ReadWriteOnce
  sizeData: 8Gi
  sizeBackup: 30Gi
  storageClassNameData: sc-data-disk
  storageClassNameBackup: sc-backup-disk

phpmyadmin:
   enable: false
   labels: {}
   serviceType: ClusterIP

