#apiVersion: external-secrets.io/v1beta1
#kind: ExternalSecret
#metadata:
#  name: mariadb-es
#spec:
#  refreshInterval: "3600s"
#  secretStoreRef:
#    name: vault-backend
#    kind: ClusterSecretStore
#  target:
#    name: mariadb-secret
#  data:
#  - secretKey: root-password
#    remoteRef:
#      key: secret/mariadb
#      property: root-password 


apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
  data:
  - secretKey: root-password
    remoteRef:
      key: secret/mariadb
      property: root-password