apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: docker-registry-credentials  # Hier wird der externe Secret-Manager referenziert
      template:
        templateFrom:
          - data:
              .dockerconfigjson: |
                {
                  "auths": {
                    "{{ .Values.externalSecret.dockerCredentials.urlKey }}": {
                      "username": "{{ .Values.externalSecret.dockerCredentials.userKey }}",
                      "password": "{{ .Values.externalSecret.dockerCredentials.passwordKey }}",
                      "email": "{{ .Values.externalSecret.dockerCredentials.emailKey }}",
                      "auth": "{{ printf "%s:%s" .Values.externalSecret.dockerCredentials.userKey .Values.externalSecret.dockerCredentials.passwordKey | b64enc }}"
                    }
                  }
                }

