apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key | quote }}  
        property: {{ .Values.externalSecret.remoteRef.property }}
      

